"""Paletas, traduções e estado visual compartilhado do desktop."""

TEXTS = {
    "en": {"library":"Library","collections":"Collections","theme":"Theme","fit":"⊞ Fit","fullscreen":"⛶ Fullscreen","language":"Choose Language","choose_library_folder":"Choose Library Folder","error":"Error","back":"← Back","no_comics":"No comics found","add_folder":"Choose a folder","light":"Light Mode","dark":"Dark Mode","folder":"Folder","manga_off":"🇯🇵 Manga OFF","manga_on":"🇯🇵 Manga ON","no_collections":"No collections found","issues":"issue","back_collections":"← Collections","all":"All","subfolders":"Folders","series":"Series","sort_name":"Name","sort_date":"Date","sort_progress":"Progress","read":"read","continue_reading":"▶ Continue","sort_by":"Sort:","unread":"Unread","search":"Search…","no_results":"No results for","loading":"Loading…","continue_section":"Continue Reading","next_issue":"Next issue","next_chapter_q":"Next issue of the series?","yes":"Yes","no":"No","bookmark":"Bookmark","immersive":"Immersive","rotate":"Rotate","brightness":"Brightness","double_page":"Double Page","filter_status":"Status","f_all":"All","f_unread":"Unread","f_reading":"Reading","f_done":"Done"},
    "pt": {"library":"Biblioteca","collections":"Coleções","theme":"Tema","fit":"⊞ Encaixar","fullscreen":"⛶ Tela Cheia","language":"Escolha o Idioma","choose_library_folder":"Escolher Pasta","error":"Erro","back":"← Voltar","no_comics":"Nenhuma história encontrada","add_folder":"Escolher pasta","light":"Modo Claro","dark":"Modo Escuro","folder":"Pasta","manga_off":"🇯🇵 Mangá OFF","manga_on":"🇯🇵 Mangá ON","no_collections":"Nenhuma coleção encontrada","issues":"edição","back_collections":"← Coleções","all":"Todas","subfolders":"Pastas","series":"Séries","sort_name":"Nome","sort_date":"Data","sort_progress":"Progresso","read":"lidas","continue_reading":"▶ Continuar","sort_by":"Ordenar:","unread":"Não lido","search":"Buscar…","no_results":"Nenhum resultado para","loading":"Carregando…","continue_section":"Continuar Lendo","next_issue":"Próxima edição","next_chapter_q":"Próxima edição da série?","yes":"Sim","no":"Não","bookmark":"Marcador","immersive":"Imersivo","rotate":"Girar","brightness":"Brilho","double_page":"Página Dupla","filter_status":"Status","f_all":"Todos","f_unread":"Não lidos","f_reading":"Lendo","f_done":"Concluídos"},
}
DARK={"bg":"#0d0d12","surface":"#161620","surface_alt":"#1e1e2c","surface_hover":"#252536","border":"#2a2a40","border_glow":"#c44a2a","accent":"#cc2222","accent2":"#ff6644","text":"#ede8e0","text_dim":"#6b6680","text_muted":"#3a3850","canvas_bg":"#07070e","btn_hover":"#2a2a3e","progress_bg":"#1e1e2c","shadow":"#000000","shadow_light":"#1a1a2e","read_badge":"#2a5c3a","read_badge_text":"#5dde8a","search_bg":"#1a1a28"}
LIGHT={"bg":"#f0ede8","surface":"#ffffff","surface_alt":"#f7f5f2","surface_hover":"#ede9e4","border":"#d4cfc8","border_glow":"#d4603e","accent":"#cc2222","accent2":"#ff6644","text":"#1a1812","text_dim":"#8a8070","text_muted":"#ccc8c0","canvas_bg":"#e8e4de","btn_hover":"#e5e0d8","progress_bg":"#e0dbd4","shadow":"#aaaaaa","shadow_light":"#d4cfc8","read_badge":"#d4f0dc","read_badge_text":"#1a7a3a","search_bg":"#f0ede8"}

