
TEXTS = {
    "en": {"library":"Library","collections":"Collections","theme":"Theme","fit":"⊞ Fit","fullscreen":"⛶ Fullscreen","language":"Choose Language","choose_library_folder":"Choose Library Folder","error":"Error","back":"← Back","no_comics":"No comics found","add_folder":"Choose a folder","light":"Light Mode","dark":"Dark Mode","folder":"Folder","manga_off":"🇯🇵 Manga OFF","manga_on":"🇯🇵 Manga ON","no_collections":"No collections found","issues":"issue","back_collections":"← Collections","all":"All","subfolders":"Folders","series":"Series","sort_name":"Name","sort_date":"Date","sort_progress":"Progress","read":"read","continue_reading":"▶ Continue","sort_by":"Sort:","unread":"Unread","search":"Search…","no_results":"No results for","loading":"Loading…","continue_section":"Continue Reading","next_issue":"Next issue","next_chapter_q":"Next issue of the series?","yes":"Yes","no":"No","bookmark":"Bookmark","immersive":"Immersive","rotate":"Rotate","brightness":"Brightness","double_page":"Double Page","filter_status":"Status","f_all":"All","f_unread":"Unread","f_reading":"Reading","f_done":"Done"},
    "pt": {"library":"Biblioteca","collections":"Coleções","theme":"Tema","fit":"⊞ Encaixar","fullscreen":"⛶ Tela Cheia","language":"Escolha o Idioma","choose_library_folder":"Escolher Pasta","error":"Erro","back":"← Voltar","no_comics":"Nenhuma história encontrada","add_folder":"Escolher pasta","light":"Modo Claro","dark":"Modo Escuro","folder":"Pasta","manga_off":"🇯🇵 Mangá OFF","manga_on":"🇯🇵 Mangá ON","no_collections":"Nenhuma coleção encontrada","issues":"edição","back_collections":"← Coleções","all":"Todas","subfolders":"Pastas","series":"Séries","sort_name":"Nome","sort_date":"Data","sort_progress":"Progresso","read":"lidas","continue_reading":"▶ Continuar","sort_by":"Ordenar:","unread":"Não lido","search":"Buscar…","no_results":"Nenhum resultado para","loading":"Carregando…","continue_section":"Continuar Lendo","next_issue":"Próxima edição","next_chapter_q":"Próxima edição da série?","yes":"Sim","no":"Não","bookmark":"Marcador","immersive":"Imersivo","rotate":"Girar","brightness":"Brilho","double_page":"Página Dupla","filter_status":"Status","f_all":"Todos","f_unread":"Não lidos","f_reading":"Lendo","f_done":"Concluídos"},
}




DARK={"bg":"#0a0a10","surface":"#15151f","surface_alt":"#1c1c29","surface_hover":"#26263a","border":"#2e2e46","border_glow":"#e2733f","accent":"#df3b3b","accent2":"#ff7a4d","text":"#f2ede4","text_dim":"#9089a8","text_muted":"#403e5c","canvas_bg":"#05050a","btn_hover":"#2e2e46","progress_bg":"#22222f","shadow":"#000000","shadow_light":"#1c1c2c","read_badge":"#234a30","read_badge_text":"#6ee69a","search_bg":"#1c1c2c"}
LIGHT={"bg":"#faf8f5","surface":"#ffffff","surface_alt":"#f4f1eb","surface_hover":"#ece7de","border":"#e2dbd0","border_glow":"#e2733f","accent":"#d6362f","accent2":"#ff7a4d","text":"#211f1a","text_dim":"#7d7566","text_muted":"#d8d2c6","canvas_bg":"#efece5","btn_hover":"#ece7de","progress_bg":"#e6e0d5","shadow":"#c4bdae","shadow_light":"#e2dbd0","read_badge":"#dcf3e2","read_badge_text":"#1c7a3e","search_bg":"#f4f1eb"}